###############################################################################
# Copyright (c) 2020, 2020 IBM Corp. and others
#
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which accompanies this
# distribution and is available at https://www.eclipse.org/legal/epl-2.0/
# or the Apache License, Version 2.0 which accompanies this distribution and
# is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# This Source Code may also be made available under the following
# Secondary Licenses when the conditions for such availability set
# forth in the Eclipse Public License, v. 2.0 are satisfied: GNU
# General Public License, version 2 with the GNU Classpath
# Exception [1] and GNU General Public License, version 2 with the
# OpenJDK Assembly Exception [2].
#
# [1] https://www.gnu.org/software/classpath/license.html
# [2] http://openjdk.java.net/legal/assembly-exception.html
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception
###############################################################################
name: "nightly build-openj9"
on:
  schedule:
    - cron:  '30 21 * * 1-5'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-10.15, windows-2016]
        version: [8, 11, 16]
        exclude:
        # excludes jdk 8 on Mac( not valid), jdk8 on windows( not enabled), jdk11 on windows( issue opened)
          - os: macos-10.15
            version: 8
          - os: windows-2016
            version: 8 
          - os: windows-2016
            version: 11 #https://github.com/eclipse/build-openj9/issues/2
    steps:
    - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1.2.0
    - uses: eclipse/build-openj9@v1
      id: buildJDK
      with: 
        version: ${{ matrix.version }}
    - run: ${{ steps.buildJDK.outputs.BuildJDKDir }}/bin/java -version
