name: "test"
on:
  push:
    branches-ignore:
      - '**'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2016, ubuntu-18.04, macos-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: eclipse/build-openj9@v1
      id: buildJDK
      with: 
        version: 11
    - run: ${{ steps.buildJDK.outputs.BuildJDKDir }}/bin/java -version
